#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "regenerate-agents-md.py"


class RegenerateAgentsMdTests(unittest.TestCase):
    def _create_test_agentdesk(self, root: Path) -> Path:
        agentdesk = root / "AgentDesk"
        guidance = agentdesk / "global-guidance"
        guidance.mkdir(parents=True)
        components = guidance / "agents-md-components"
        components.mkdir()
        (components / "common-rule.md").write_text("# Common rule\n\ncommon rule\n", encoding="utf-8")
        (guidance / "agents-md-manifest.yaml").write_text(
            "version: 1\ncomponents:\n  - agents-md-components/common-rule.md\n",
            encoding="utf-8",
        )
        fake_scripts = agentdesk / "scripts"
        fake_scripts.mkdir(parents=True)
        for name in ("regenerate-agents-md.py", "bootstrap-agents-md.py", "repository_registry.py"):
            (fake_scripts / name).write_text((ROOT / "scripts" / name).read_text(encoding="utf-8"), encoding="utf-8")
        return fake_scripts / "regenerate-agents-md.py"

    def test_defaults_codex_output_to_dot_codex_under_home(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            script = self._create_test_agentdesk(root)
            home = root / "home"
            home.mkdir()
            (home / "AGENTS.md").write_text(
                "<!-- Generated by AgentDesk bootstrap-agents-md.py. Do not edit. -->\nlegacy\n",
                encoding="utf-8",
            )
            env = {**os.environ, "HOME": str(home)}
            env.pop("CODEX_HOME", None)

            subprocess.run([
                sys.executable, str(script),
                "--claude-home", str(root / ".claude"),
                "--opencode-home", str(root / ".config" / "opencode"),
            ], check=True, env=env)

            rendered = (home / ".codex" / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("common rule", rendered)
            self.assertIn("bootstrap-agents-md.py", rendered)
            self.assertFalse((home / "AGENTS.md").exists())

    def test_codex_home_environment_override_is_expanded(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            script = self._create_test_agentdesk(root)
            home = root / "home"
            env = {**os.environ, "HOME": str(home), "CODEX_HOME": "~/custom-codex"}

            subprocess.run([
                sys.executable, str(script),
                "--claude-home", str(root / ".claude"),
                "--opencode-home", str(root / ".config" / "opencode"),
            ], check=True, env=env)

            rendered = (home / "custom-codex" / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("common rule", rendered)
            self.assertFalse((home / "AGENTS.md").exists())


if __name__ == "__main__":
    unittest.main()
