#!/usr/bin/env python3
"""Install global entrypoints to reconciled, repo-backed agent guidance."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile

import yaml



GENERATED_MARKER = "<!-- Generated by AgentDesk bootstrap-agents-md.py. Do not edit. -->"
LEGACY_GENERATED_MARKERS = {
    "<!-- Generated by SkillPort bootstrap-agent-guidance.py. Do not edit. -->",
    "<!-- Generated by SkillPort bootstrap-agents-md.py. Do not edit. -->",
}

RUNTIME_AGENT_MARKER = "<!-- Generated by AgentDesk runtime-mode sync. Do not edit. -->"
LAYER_SET_PATTERN = re.compile(r"^<!-- AgentDesk layer set: ([0-9a-f]{16}) -->$", re.MULTILINE)


def _default_codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")).expanduser()

def _layer_set_marker(layer_set: str | None) -> str:
    return f"<!-- AgentDesk layer set: {layer_set} -->" if layer_set else ""


def _content_layer_set(content: str) -> str | None:
    match = LAYER_SET_PATTERN.search(content)
    return match.group(1) if match else None


def _sync_runtime_agents(sources: dict[str, Path], destination_dir: Path,
                         replace: bool = False, dry_run: bool = False,
                         layer_set: str | None = None,
                         validate_only: bool = False) -> None:
    if destination_dir.exists() and not destination_dir.is_dir():
        raise ValueError(f"Expected runtime guidance directory, found non-directory: {destination_dir}")
    ownership_file = destination_dir / ".agentdesk-layer-set"
    recorded_owner = ownership_file.read_text(encoding="utf-8").strip() if ownership_file.is_file() else None
    has_existing_entries = destination_dir.is_dir() and any(destination_dir.iterdir())
    if has_existing_entries and recorded_owner != layer_set and (recorded_owner is not None or layer_set is not None) and not replace:
        raise ValueError(f"Runtime guidance layer ownership differs; reconcile before --replace-existing: {destination_dir}")
    desired = set(sources)
    planned: list[tuple[Path, str]] = []
    layer_marker = _layer_set_marker(layer_set)
    for name, source in sorted(sources.items()):
        if source.suffix == ".md":
            prefix = f"{RUNTIME_AGENT_MARKER}\n"
            if layer_marker:
                prefix += f"{layer_marker}\n"
            content = f"{prefix}\n{source.read_text(encoding='utf-8').strip()}\n"
        else:
            content = source.read_text(encoding="utf-8")
        destination = destination_dir / name
        if destination.exists() and destination.read_text(encoding="utf-8", errors="replace") == content:
            continue
        if destination.exists():
            existing = destination.read_text(encoding="utf-8", errors="replace")
            generated = existing.startswith(RUNTIME_AGENT_MARKER) or source.suffix == ".json" and recorded_owner == layer_set
            same_owner = _content_layer_set(existing) == layer_set or source.suffix == ".json" and recorded_owner == layer_set
            if not replace and not (generated and same_owner):
                raise ValueError(f"Runtime guidance ownership differs; reconcile before --replace-existing: {destination}")
        planned.append((destination, content))

    stale: list[Path] = []
    for destination in [*destination_dir.glob("*.md"), *destination_dir.glob("*.json")]:
        if destination.name in desired:
            continue
        existing = destination.read_text(encoding="utf-8", errors="replace")
        if not existing.startswith(RUNTIME_AGENT_MARKER) or _content_layer_set(existing) != layer_set:
            continue
        stale.append(destination)

    if validate_only:
        return
    for destination, content in planned:
        print(f"{'Would install' if dry_run else 'Install'} runtime guidance: {destination}")
        if not dry_run:
            _atomic_write(destination, content)
    for destination in stale:
        print(f"{'Would remove' if dry_run else 'Remove'} stale runtime guidance: {destination}")
        if not dry_run:
            destination.unlink()
    if not dry_run:
        if layer_set:
            _atomic_write(ownership_file, f"{layer_set}\n")
        elif ownership_file.exists():
            ownership_file.unlink()


def _remove_legacy_codex_guidance(legacy_home: Path, agents_home: Path, dry_run: bool = False) -> None:
    legacy_home = legacy_home.resolve()
    agents_home = agents_home.resolve()
    if legacy_home == agents_home:
        return

    legacy_agents = legacy_home / "AGENTS.md"
    if legacy_agents.is_file():
        existing = legacy_agents.read_text(encoding="utf-8", errors="replace")
        if existing.startswith(GENERATED_MARKER) or any(existing.startswith(marker) for marker in LEGACY_GENERATED_MARKERS):
            print(f"{'Would remove' if dry_run else 'Remove'} legacy generated guidance: {legacy_agents}")
            if not dry_run:
                legacy_agents.unlink()

    legacy_refs = legacy_home / "agents-md-references"
    current_refs = agents_home / "agents-md-references"
    if not legacy_refs.is_dir():
        return
    for legacy in legacy_refs.iterdir():
        if not legacy.is_file():
            continue
        existing = legacy.read_text(encoding="utf-8", errors="replace")
        generated = existing.startswith(RUNTIME_AGENT_MARKER)
        current = current_refs / legacy.name
        identical_generated_copy = current.is_file() and legacy.read_bytes() == current.read_bytes()
        if not (generated or identical_generated_copy):
            continue
        print(f"{'Would remove' if dry_run else 'Remove'} legacy generated guidance: {legacy}")
        if not dry_run:
            legacy.unlink()
    if not dry_run and legacy_refs.is_dir() and not any(legacy_refs.iterdir()):
        legacy_refs.rmdir()


def _atomic_write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _apply_plans(plans: list[tuple[Path, str, bool, bool]], replace: bool,
                 dry_run: bool, protected_sources: set[Path]) -> None:
    pending = []
    for destination, content, link, managed in plans:
        resolved_destination = destination.resolve() if destination.exists() else destination.absolute()
        if resolved_destination in protected_sources:
            if link and destination.is_symlink():
                continue
            raise ValueError(f"Destination must not overwrite source: {destination}")
        exists = destination.exists() or destination.is_symlink()
        if destination.is_dir():
            raise ValueError(f"Expected a file, found a directory: {destination}")
        if exists and not link and not destination.is_symlink():
            if destination.read_text(encoding="utf-8") == content:
                continue
        existing_text = (
            destination.read_text(encoding="utf-8", errors="replace")
            if exists and not destination.is_symlink()
            else ""
        )
        generated = bool(existing_text) and (
            existing_text.startswith(GENERATED_MARKER)
            or any(existing_text.startswith(marker) for marker in LEGACY_GENERATED_MARKERS)
        )
        same_owner = _content_layer_set(existing_text) == _content_layer_set(content)
        if exists and not replace and not (managed and generated and same_owner):
            raise ValueError(f"Reconcile existing preferences before --replace-existing: {destination}")
        pending.append((destination, content, link, exists, generated))

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    for destination, content, link, exists, generated in pending:
        print(f"{'Would install' if dry_run else 'Install'} {'symlink' if link else 'generated/reference'}: {destination}")
        if dry_run:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if exists:
            if not generated:
                backup = destination.parent / "guidance-backups" / stamp / destination.name
                backup.parent.mkdir(parents=True, exist_ok=True)
                if destination.is_symlink():
                    _atomic_write(backup, destination.read_text(encoding="utf-8"))
                else:
                    shutil.copy2(destination, backup)
            destination.unlink()
        if link:
            destination.symlink_to(next(iter(protected_sources)))
        else:
            _atomic_write(destination, content)
        assert destination.read_text(encoding="utf-8") == (
            next(iter(protected_sources)).read_text(encoding="utf-8") if link else content
        )


def install(source: Path, agents_home: Path, claude_home: Path,
            replace: bool = False, dry_run: bool = False,
            opencode_home: Path | None = None) -> None:
    source = source.resolve(strict=True)
    if not source.is_file() or not source.read_text(encoding="utf-8").strip():
        raise ValueError("Source must be a nonempty UTF-8 guidance file")
    agents = agents_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = agents_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")
    wrapper = ("Before responding or taking action, read the complete shared personal "
               f"instructions at `{source.as_posix()}` and follow them for this task. "
               "If the file cannot be read, report the missing source. "
               "Edit that repository source when updating these rules, not this wrapper.\n")
    # Claude treats the remainder of a one-line import as the path, including
    # spaces. Codex uses a symlink and OpenCode stores a JSON string.
    imports = f"@{source.as_posix()}\n"
    plans = [(agents, wrapper, os.name != "nt"), (claude, imports, False)]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(p, str) for p in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        if source.as_posix() not in instructions:
            data["instructions"] = [*instructions, source.as_posix()]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False))
    _apply_plans([(path, content, link, False) for path, content, link in plans],
                 replace, dry_run, {source})


class GuidanceComponent:
    def __init__(self, path: Path, text: str, children: tuple["GuidanceComponent", ...] = ()) -> None:
        self.path = path
        self.text = text
        self.children = children


class GuidanceLayer:
    def __init__(self, manifest: Path, layer_id: str, components: list[GuidanceComponent],
                 references: dict[str, Path]) -> None:
        self.manifest = manifest
        self.layer_id = layer_id
        self.components = components
        self.references = references


def _load_manifest_layer(manifest_path: Path, base: bool = False) -> GuidanceLayer:
    manifest_path = manifest_path.resolve(strict=True)
    root = manifest_path.parent
    data = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Guidance manifest must be a mapping")
    raw_components = data.get("components")
    if not isinstance(raw_components, list) or not raw_components:
        raise ValueError("Guidance manifest must declare at least one component")
    layer_id = data.get("layer_id", "base" if base else None)
    if not isinstance(layer_id, str) or not re.fullmatch(r"[a-z0-9][a-z0-9._-]{0,63}", layer_id):
        raise ValueError(f"Overlay manifest must declare a portable layer_id: {manifest_path}")

    seen: set[Path] = set()

    def resolve_owned(relative: str | Path) -> Path:
        source = (root / relative).resolve(strict=True)
        try:
            source.relative_to(root)
        except ValueError as error:
            raise ValueError(f"Guidance source must remain inside its manifest directory: {relative}") from error
        return source

    def parse(entry: object) -> GuidanceComponent:
        if isinstance(entry, str):
            relative = entry
            raw_children: list[object] = []
        elif isinstance(entry, dict):
            relative = entry.get("path")
            raw_children = entry.get("children", [])
            if not isinstance(relative, str) or not relative.strip():
                raise ValueError("Nested guidance component must declare a nonempty path")
            if not isinstance(raw_children, list):
                raise ValueError(f"children must be a list for guidance component: {relative}")
        else:
            raise ValueError("Guidance components must be paths or {path, children} mappings")

        source = resolve_owned(relative)
        if source in seen:
            raise ValueError(f"Duplicate guidance component in manifest: {relative}")
        text = source.read_text(encoding="utf-8").strip()
        if not text:
            raise ValueError(f"Guidance component must be nonempty: {source}")
        seen.add(source)
        return GuidanceComponent(source, text, tuple(parse(child) for child in raw_children))

    components = [parse(entry) for entry in raw_components]
    references_dir = root / "agents-md-references"
    references: dict[str, Path] = {}
    if references_dir.exists() and not references_dir.is_dir():
        raise ValueError(f"Expected agents-md-references directory: {references_dir}")
    if references_dir.is_dir():
        for source in sorted(references_dir.iterdir()):
            if source.is_file() and source.suffix in {".md", ".json"}:
                references[source.name] = resolve_owned(source.relative_to(root))
    return GuidanceLayer(manifest_path, layer_id, components, references)


def _load_manifest(manifest_path: Path) -> list[GuidanceComponent]:
    return _load_manifest_layer(manifest_path, base=True).components


def _load_layers(manifest: Path, overlay_manifests: list[Path]) -> list[GuidanceLayer]:
    manifest_paths = [manifest.resolve(strict=True), *(path.resolve(strict=True) for path in overlay_manifests)]
    if len(set(manifest_paths)) != len(manifest_paths):
        raise ValueError("Each guidance manifest may be supplied only once")
    layers = [_load_manifest_layer(path, base=index == 0) for index, path in enumerate(manifest_paths)]
    layer_ids = [layer.layer_id for layer in layers]
    if len(set(layer_ids)) != len(layer_ids):
        raise ValueError("Each guidance layer_id must be unique")

    anchors: dict[str, Path] = {}
    references: dict[str, Path] = {}
    for layer in layers:
        for component in _flatten_components(layer.components):
            _, anchor = _component_heading(component)
            if anchor in anchors:
                raise ValueError(f"Duplicate guidance heading anchor '{anchor}': {anchors[anchor]} and {component.path}")
            anchors[anchor] = component.path
        for name, source in layer.references.items():
            if name in references:
                raise ValueError(f"Conflicting runtime guidance destination '{name}': {references[name]} and {source}")
            references[name] = source
    return layers


def _flatten_components(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...]) -> list[GuidanceComponent]:
    flattened: list[GuidanceComponent] = []
    for component in components:
        flattened.append(component)
        flattened.extend(_flatten_components(component.children))
    return flattened


def _component_heading(component: GuidanceComponent) -> tuple[str, str]:
    heading_match = re.search(r'^#\s+(.+)$', component.text, flags=re.MULTILINE)
    if not heading_match:
        raise ValueError(f"Guidance component must declare an H1 heading for TOC generation: {component.path}")
    heading = heading_match.group(1)
    anchor_match = re.search(r'<a id="([^"]+)"></a>', component.text)
    if anchor_match:
        anchor = anchor_match.group(1)
    else:
        anchor = re.sub(r'[^a-z0-9 -]', '', heading.lower())
        anchor = re.sub(r'\s+', '-', anchor.strip())
    return heading, anchor


def _component_toc_lines(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...], depth: int = 0) -> list[str]:
    toc: list[str] = []
    for component in components:
        heading, anchor = _component_heading(component)
        toc.append(f"{'  ' * depth}- [{heading}](#{anchor})")
        if anchor == "workspace-and-agent-system":
            toc.append(f"{'  ' * (depth + 1)}- [🛠️ Updating this AGENTS.md](#agents-md-maintenance)")
        toc.extend(_component_toc_lines(component.children, depth + 1))
    return toc


def _demote_markdown_headings(text: str, depth: int) -> str:
    if depth == 0:
        return text
    rendered: list[str] = []
    in_fence = False
    fence_marker = ""
    for line in text.splitlines():
        stripped = line.lstrip()
        marker = stripped[:3]
        if marker in {"```", "~~~"}:
            if not in_fence:
                in_fence = True
                fence_marker = marker
            elif marker == fence_marker:
                in_fence = False
                fence_marker = ""
            rendered.append(line)
            continue
        if not in_fence:
            match = re.match(r'^(#{1,6})(\s+.*)$', line)
            if match:
                level = min(6, len(match.group(1)) + depth)
                line = f"{'#' * level}{match.group(2)}"
        rendered.append(line)
    return "\n".join(rendered)


def _local_toc(component: GuidanceComponent, depth: int) -> str:
    if not component.children:
        return ""
    heading_level = min(6, depth + 2)
    lines = [f"{'#' * heading_level} 🗂️ Contents", ""]
    _, anchor = _component_heading(component)
    if anchor == "workspace-and-agent-system":
        lines.append("- [🛠️ Updating this AGENTS.md](#agents-md-maintenance)")
    for child in component.children:
        heading, anchor = _component_heading(child)
        lines.append(f"- [{heading}](#{anchor})")
    return "\n".join(lines)


def _render_component_blocks(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...], depth: int = 0,
                             maintenance_text: str | None = None) -> list[str]:
    blocks: list[str] = []
    for component in components:
        if depth == 0:
            blocks.append("<br><br>")
            blocks.append("---")
        blocks.append(_demote_markdown_headings(component.text, depth))
        local_toc = _local_toc(component, depth)
        if local_toc:
            blocks.append(local_toc)
        _, anchor = _component_heading(component)
        if anchor == "workspace-and-agent-system" and maintenance_text is not None:
            blocks.append(maintenance_text)
        blocks.extend(_render_component_blocks(component.children, depth + 1, maintenance_text))
    return blocks

def install_layered(manifest: Path, agents_home: Path, claude_home: Path,
                    replace: bool = False, dry_run: bool = False,
                    opencode_home: Path | None = None,
                    agents_path_label: str | None = None,
                    link_base: Path | None = None,
                    overlay_manifests: list[Path] | None = None) -> None:
    manifest = manifest.resolve(strict=True)
    layers = _load_layers(manifest, overlay_manifests or [])
    component_tree = [component for layer in layers for component in layer.components]
    components = _flatten_components(component_tree)
    agents_home = agents_home.resolve()
    link_base = (link_base or agents_home).resolve()
    claude_home = claude_home.resolve()
    if opencode_home is not None:
        opencode_home = opencode_home.resolve()
    for target_home in [agents_home, claude_home, opencode_home]:
        if target_home is not None and target_home.exists() and not target_home.is_dir():
            raise ValueError(f"Expected harness home directory, found non-directory: {target_home}")

    has_workspace_group = any(
        _component_heading(component)[1] == "workspace-and-agent-system"
        for component in component_tree
    )
    component_toc_lines = _component_toc_lines(component_tree)
    if not has_workspace_group:
        component_toc_lines.insert(0, "- [🛠️ Updating this AGENTS.md](#agents-md-maintenance)")
    component_toc_text = "\n".join(component_toc_lines)
    manifest_links = [Path(os.path.relpath(layer.manifest, start=link_base)).as_posix() for layer in layers]
    manifest_link = manifest_links[0]
    component_links = [Path(os.path.relpath(component.path, start=link_base)).as_posix() for component in components]
    regenerate_link = Path(os.path.relpath(Path(__file__).with_name("regenerate-agents-md.py").resolve(), start=link_base)).as_posix()
    protected_sources = {component.path for component in components} | {layer.manifest for layer in layers}
    if len(layers) == 1:
        source_lines = [
            "This file is generated atomically from the ordered sources declared in:",
            "",
            f"- [AGENTS.md manifest](<{manifest_link}>)",
            "",
            "Resolved order:",
            "",
            *[f"{index}. [{component.path.name}](<{link}>)" for index, (component, link) in enumerate(zip(components, component_links), start=1)],
        ]
    else:
        source_lines = [
            "This file is generated atomically from the ordered guidance layers:",
            "",
            *[f"{index}. [Manifest: {layer.layer_id}](<{link}>)" for index, (layer, link) in enumerate(zip(layers, manifest_links), start=1)],
            "",
            "Resolved component order:",
            "",
            *[f"{index}. [{component.path.name}](<{link}>)" for index, (component, link) in enumerate(zip(components, component_links), start=1)],
        ]
    source_text = "\n".join(source_lines)
    maintenance_text = (
        '<a id="agents-md-maintenance"></a>\n'
        f"{'##' if has_workspace_group else '#'} 🛠️ Updating this AGENTS.md\n\n"
        f"{source_text}\n\n"
        "| When | Then |\n"
        "| --- | --- |\n"
        f"| Updating global agent guidance. | Change the manifest, its canonical components, or generated `agents-md-references/*.md` sources in AgentDesk; do not edit generated files under the agent home directly. Run [`regenerate-agents-md.py`](<{regenerate_link}>) after changing canonical sources. |\n"
        "| A rule determines whether a reference file should be opened. | Put that `when` condition in the applicable AGENTS.md component before the reference is loaded. Put only post-load instructions in the referenced file; do not put sibling-routing or progressive-disclosure logic inside the reference. |\n"
        "| Resolving a relative Markdown link or relative path from this global guidance. | Resolve it relative to the directory containing this `AGENTS.md` (`./AGENTS.md`), never relative to the active working directory. |\n\n"
        f"**AGENTS.md absolute path:** `{agents_path_label or (agents_home / 'AGENTS.md').as_posix()}`"
    )
    component_blocks = _render_component_blocks(component_tree, maintenance_text=maintenance_text)
    if not has_workspace_group:
        component_blocks.insert(0, maintenance_text)
    component_text = "\n\n".join(component_blocks)
    digest_material = "\0".join([
        *(layer.manifest.read_text(encoding="utf-8") for layer in layers),
        *(component.text for component in components),
    ])
    digest = hashlib.sha256(digest_material.encode()).hexdigest()[:16]
    layer_set = None if len(layers) == 1 else hashlib.sha256("\0".join(layer.layer_id for layer in layers).encode()).hexdigest()[:16]
    layer_set_line = f"{_layer_set_marker(layer_set)}\n" if layer_set else ""
    rendered = (
        f"{GENERATED_MARKER}\n"
        f"{layer_set_line}"
        f"<!-- Source digest: {digest} -->\n\n"
        "## 🗂️ Contents\n\n"
        f"{component_toc_text}\n"
        f"{component_text}\n"
    )
    agents = agents_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = agents_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")

    imports = "".join(f"@{component.path.as_posix()}\n" for component in components)
    plans: list[tuple[Path, str, bool, bool]] = [
        (agents, rendered, False, True),
        (claude, imports, False, False),
    ]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(path, str) for path in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        managed_paths = {*(component.path.as_posix() for component in components)}
        for layer in layers:
            root = layer.manifest.parent
            managed_paths.update({
                (root / "AGENTS.md").resolve(strict=False).as_posix(),
                (root / "common.md").resolve(strict=False).as_posix(),
                (root / "macos.md").resolve(strict=False).as_posix(),
                (root / "windows-wsl.md").resolve(strict=False).as_posix(),
            })
        retained = [path for path in instructions if path not in managed_paths]
        data["instructions"] = [*retained, *(component.path.as_posix() for component in components)]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False, False))
    references = {name: source for layer in layers for name, source in layer.references.items()}
    runtime_destination = agents_home / "agents-md-references"
    _sync_runtime_agents(references, runtime_destination, replace, dry_run, layer_set, validate_only=True)
    _apply_plans(plans, replace, dry_run, protected_sources)
    _sync_runtime_agents(references, runtime_destination, replace, dry_run, layer_set)
    if agents_home == _default_codex_home().resolve():
        _remove_legacy_codex_guidance(Path.home(), agents_home, dry_run)

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--source", type=Path)
    mode.add_argument("--manifest", type=Path)
    parser.add_argument("--overlay-manifest", action="append", type=Path, default=[])
    parser.add_argument("--codex-home", type=Path, default=_default_codex_home())
    parser.add_argument("--agents-home", dest="codex_home", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--opencode-home", type=Path, default=Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "opencode")
    parser.add_argument("--replace-existing", action="store_true", help="Only after merging old preferences; originals are backed up")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--link-base", type=Path, help="Compute generated Markdown links relative to this eventual AGENTS.md directory")
    parser.add_argument("--agents-path-label", help="Path label embedded in generated maintenance guidance")
    args = parser.parse_args()
    codex_home = args.codex_home.expanduser()
    if args.source:
        install(args.source, codex_home, args.claude_home, args.replace_existing, args.dry_run, args.opencode_home)
    else:
        install_layered(args.manifest, codex_home,
                        args.claude_home, args.replace_existing, args.dry_run,
                        args.opencode_home, args.agents_path_label, args.link_base,
                        args.overlay_manifest)


if __name__ == "__main__":
    main()
