#!/usr/bin/env python3
"""Install global entrypoints to a reconciled, repo-backed AGENTS.md."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import tempfile



GENERATED_MARKER = "<!-- Generated by AgentDesk bootstrap-agents-md.py. Do not edit. -->"
LEGACY_GENERATED_MARKERS = {
    "<!-- Generated by SkillPort bootstrap-agent-guidance.py. Do not edit. -->",
    "<!-- Generated by SkillPort bootstrap-agents-md.py. Do not edit. -->",
}

RUNTIME_AGENT_MARKER = "<!-- Generated by AgentDesk runtime-mode sync. Do not edit. -->"

def _sync_runtime_agents(source_dir: Path, destination_dir: Path, dry_run: bool = False) -> None:
    if not source_dir.is_dir():
        return
    destination_dir.mkdir(parents=True, exist_ok=True)
    desired: set[str] = set()
    sources = sorted(source_dir.glob("*.md")) + sorted(source_dir.glob("*.json"))
    for source in sources:
        desired.add(source.name)
        if source.suffix == ".md":
            content = f"{RUNTIME_AGENT_MARKER}\n\n{source.read_text(encoding='utf-8').strip()}\n"
        else:
            content = source.read_text(encoding="utf-8")
        destination = destination_dir / source.name
        if destination.exists() and destination.read_text(encoding="utf-8", errors="replace") == content:
            continue
        print(f"{'Would install' if dry_run else 'Install'} runtime guidance: {destination}")
        if not dry_run:
            _atomic_write(destination, content)
    for destination in [*destination_dir.glob("*.md"), *destination_dir.glob("*.json")]:
        if destination.name in desired:
            continue
        existing = destination.read_text(encoding="utf-8", errors="replace")
        if not existing.startswith(RUNTIME_AGENT_MARKER):
            continue
        print(f"{'Would remove' if dry_run else 'Remove'} stale runtime guidance: {destination}")
        if not dry_run:
            destination.unlink()


def _atomic_write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _apply_plans(plans: list[tuple[Path, str, bool, bool]], replace: bool,
                 dry_run: bool, protected_sources: set[Path]) -> None:
    pending = []
    for destination, content, link, managed in plans:
        resolved_destination = destination.resolve() if destination.exists() else destination.absolute()
        if resolved_destination in protected_sources:
            if link and destination.is_symlink():
                continue
            raise ValueError(f"Destination must not overwrite source: {destination}")
        exists = destination.exists() or destination.is_symlink()
        if destination.is_dir():
            raise ValueError(f"Expected a file, found a directory: {destination}")
        if exists and not link and not destination.is_symlink():
            if destination.read_text(encoding="utf-8") == content:
                continue
        existing_text = (
            destination.read_text(encoding="utf-8", errors="replace")
            if exists and not destination.is_symlink()
            else ""
        )
        generated = bool(existing_text) and (
            existing_text.startswith(GENERATED_MARKER)
            or any(existing_text.startswith(marker) for marker in LEGACY_GENERATED_MARKERS)
        )
        if exists and not replace and not (managed and generated):
            raise ValueError(f"Reconcile existing preferences before --replace-existing: {destination}")
        pending.append((destination, content, link, exists, generated))

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    for destination, content, link, exists, generated in pending:
        print(f"{'Would install' if dry_run else 'Install'} {'symlink' if link else 'generated/reference'}: {destination}")
        if dry_run:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if exists:
            if not generated:
                backup = destination.parent / "guidance-backups" / stamp / destination.name
                backup.parent.mkdir(parents=True, exist_ok=True)
                if destination.is_symlink():
                    _atomic_write(backup, destination.read_text(encoding="utf-8"))
                else:
                    shutil.copy2(destination, backup)
            destination.unlink()
        if link:
            destination.symlink_to(next(iter(protected_sources)))
        else:
            _atomic_write(destination, content)
        assert destination.read_text(encoding="utf-8") == (
            next(iter(protected_sources)).read_text(encoding="utf-8") if link else content
        )


def install(source: Path, codex_home: Path, claude_home: Path,
            replace: bool = False, dry_run: bool = False,
            opencode_home: Path | None = None) -> None:
    source = source.resolve(strict=True)
    if not source.is_file() or not source.read_text(encoding="utf-8").strip():
        raise ValueError("Source must be a nonempty UTF-8 guidance file")
    codex = codex_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = codex_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")
    wrapper = ("Before responding or taking action, read the complete shared personal "
               f"instructions at `{source.as_posix()}` and follow them for this task. "
               "If the file cannot be read, report the missing source. "
               "Edit that repository source when updating these rules, not this wrapper.\n")
    # Claude treats the remainder of a one-line import as the path, including
    # spaces. Codex uses a symlink and OpenCode stores a JSON string.
    imports = f"@{source.as_posix()}\n"
    plans = [(codex, wrapper, os.name != "nt"), (claude, imports, False)]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(p, str) for p in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        if source.as_posix() not in instructions:
            data["instructions"] = [*instructions, source.as_posix()]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False))
    _apply_plans([(path, content, link, False) for path, content, link in plans],
                 replace, dry_run, {source})


def _load_manifest(manifest_path: Path) -> list[tuple[Path, str]]:
    manifest_path = manifest_path.resolve(strict=True)
    root = manifest_path.parent
    components: list[str] = []
    section: str | None = None
    for raw_line in manifest_path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not raw_line.startswith(" "):
            if stripped == "components:":
                section = "components"
            else:
                section = None
            continue
        if section == "components" and stripped.startswith("- "):
            components.append(stripped[2:].strip())
    if not components:
        raise ValueError("Guidance manifest must declare at least one component")
    resolved: list[tuple[Path, str]] = []
    seen: set[Path] = set()
    for relative in components:
        source = (root / relative).resolve(strict=True)
        if source in seen:
            raise ValueError(f"Duplicate guidance component in manifest: {relative}")
        text = source.read_text(encoding="utf-8").strip()
        if not text:
            raise ValueError(f"Guidance component must be nonempty: {source}")
        seen.add(source)
        resolved.append((source, text))
    return resolved


def install_layered(manifest: Path, codex_home: Path, claude_home: Path,
                    replace: bool = False, dry_run: bool = False,
                    opencode_home: Path | None = None,
                    agents_path_label: str | None = None) -> None:
    manifest = manifest.resolve(strict=True)
    components = _load_manifest(manifest)
    guidance_root = manifest.parent
    codex_home = codex_home.resolve()
    claude_home = claude_home.resolve()
    if opencode_home is not None:
        opencode_home = opencode_home.resolve()

    component_text = "\n\n".join(text for _, text in components)
    manifest_link = Path(os.path.relpath(manifest, start=codex_home)).as_posix()
    component_links = [Path(os.path.relpath(path, start=codex_home)).as_posix() for path, _ in components]
    regenerate_link = Path(os.path.relpath(Path(__file__).with_name("regenerate-agents-md.py").resolve(), start=codex_home)).as_posix()
    protected_sources = {path for path, _ in components} | {manifest}
    source_lines = [
        "This file is generated atomically from the ordered sources declared in:",
        "",
        f"- [AGENTS.md manifest](<{manifest_link}>)",
        "",
        "Resolved order:",
        "",
        *[f"{index}. [Global guidance component: {path.name}](<{link}>)" for index, ((path, _), link) in enumerate(zip(components, component_links), start=1)],
    ]
    source_text = "\n".join(source_lines)
    digest_material = "\0".join([manifest.read_text(encoding="utf-8"), *(text for _, text in components)])
    digest = hashlib.sha256(digest_material.encode()).hexdigest()[:16]
    rendered = (
        f"{GENERATED_MARKER}\n"
        f"<!-- Source digest: {digest} -->\n\n"
        "## 🗂️ Contents\n\n"
        "- [🛠️ Updating this AGENTS.md](#agents-md-maintenance)\n"
        "- [🧭 ChatGPT runtime mode identification](#chatgpt-runtime-mode)\n"
        "- [🔀 Git workflow for all GitHub repositories](#git-workflow)\n"
        "- [🧰 Managed repositories, skills, and global rules](#managed-rules)\n"
        "<a id=\"agents-md-maintenance\"></a>\n"
        "# 🛠️ Updating this AGENTS.md\n\n"
        f"{source_text}\n\n"
        "To update this file, change the manifest, its components, or generated `agents-md-references/*.md` references in the AgentDesk repository and then run "
        f"[`regenerate-agents-md.py`](<{regenerate_link}>) from the AgentDesk checkout. "
        "Do not edit generated files under the agent home directly.\n\n"
        "**Progressive disclosure rule:** Put every condition that determines whether a reference file "
        "should be opened (`when`) in the applicable AGENTS.md component, before the reference is loaded. Put only the "
        "instructions that apply after loading (`what`) in the referenced `agents-md-references/*.md` file. A reference "
        "file must not contain rules about whether it should have been opened, whether sibling references "
        "should be loaded, or how progressive disclosure itself should work.\n\n"
        f"**AGENTS.md absolute path:** `{agents_path_label or (codex_home / 'AGENTS.md').as_posix()}`\n\n"
        "**Path rule for agents:** Resolve every relative Markdown link and every relative path in this "
        "file relative to the directory containing this `AGENTS.md` (that is, relative to `./AGENTS.md`), "
        "never relative to the active working directory.\n\n"
        f"{component_text}\n"
    )
    codex = codex_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = codex_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")

    imports = "".join(f"@{path.as_posix()}\n" for path, _ in components)
    plans: list[tuple[Path, str, bool, bool]] = [
        (codex, rendered, False, True),
        (claude, imports, False, False),
    ]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(path, str) for path in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        legacy = (guidance_root / "AGENTS.md").resolve(strict=False).as_posix()
        legacy_common = (guidance_root / "common.md").resolve(strict=False).as_posix()
        legacy_overlays = {
            (guidance_root / "macos.md").resolve(strict=False).as_posix(),
            (guidance_root / "windows-wsl.md").resolve(strict=False).as_posix(),
        }
        managed_paths = {legacy, legacy_common, *legacy_overlays, *(path.as_posix() for path, _ in components)}
        retained = [path for path in instructions if path not in managed_paths]
        data["instructions"] = [*retained, *(path.as_posix() for path, _ in components)]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False, False))
    _apply_plans(plans, replace, dry_run, protected_sources)
    _sync_runtime_agents(guidance_root / "agents-md-references", codex_home / "agents-md-references", dry_run)

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--source", type=Path)
    mode.add_argument("--manifest", type=Path)
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")))
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--opencode-home", type=Path, default=Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "opencode")
    parser.add_argument("--replace-existing", action="store_true", help="Only after merging old preferences; originals are backed up")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.source:
        install(args.source, args.codex_home, args.claude_home, args.replace_existing, args.dry_run, args.opencode_home)
    else:
        install_layered(args.manifest, args.codex_home,
                        args.claude_home, args.replace_existing, args.dry_run,
                        args.opencode_home)


if __name__ == "__main__":
    main()
