#!/usr/bin/env python3
"""Install global entrypoints to reconciled, repo-backed agent guidance."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile

import yaml



GENERATED_MARKER = "<!-- Generated by AgentDesk bootstrap-agents-md.py. Do not edit. -->"
LEGACY_GENERATED_MARKERS = {
    "<!-- Generated by SkillPort bootstrap-agent-guidance.py. Do not edit. -->",
    "<!-- Generated by SkillPort bootstrap-agents-md.py. Do not edit. -->",
}

RUNTIME_AGENT_MARKER = "<!-- Generated by AgentDesk runtime-mode sync. Do not edit. -->"


def _default_codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")).expanduser()

def _sync_runtime_agents(source_dir: Path, destination_dir: Path, dry_run: bool = False) -> None:
    if not source_dir.is_dir():
        return
    destination_dir.mkdir(parents=True, exist_ok=True)
    desired: set[str] = set()
    sources = sorted(source_dir.glob("*.md")) + sorted(source_dir.glob("*.json"))
    for source in sources:
        desired.add(source.name)
        if source.suffix == ".md":
            content = f"{RUNTIME_AGENT_MARKER}\n\n{source.read_text(encoding='utf-8').strip()}\n"
        else:
            content = source.read_text(encoding="utf-8")
        destination = destination_dir / source.name
        if destination.exists() and destination.read_text(encoding="utf-8", errors="replace") == content:
            continue
        print(f"{'Would install' if dry_run else 'Install'} runtime guidance: {destination}")
        if not dry_run:
            _atomic_write(destination, content)
    for destination in [*destination_dir.glob("*.md"), *destination_dir.glob("*.json")]:
        if destination.name in desired:
            continue
        existing = destination.read_text(encoding="utf-8", errors="replace")
        if not existing.startswith(RUNTIME_AGENT_MARKER):
            continue
        print(f"{'Would remove' if dry_run else 'Remove'} stale runtime guidance: {destination}")
        if not dry_run:
            destination.unlink()


def _remove_legacy_codex_guidance(legacy_home: Path, agents_home: Path, dry_run: bool = False) -> None:
    legacy_home = legacy_home.resolve()
    agents_home = agents_home.resolve()
    if legacy_home == agents_home:
        return

    legacy_agents = legacy_home / "AGENTS.md"
    if legacy_agents.is_file():
        existing = legacy_agents.read_text(encoding="utf-8", errors="replace")
        if existing.startswith(GENERATED_MARKER) or any(existing.startswith(marker) for marker in LEGACY_GENERATED_MARKERS):
            print(f"{'Would remove' if dry_run else 'Remove'} legacy generated guidance: {legacy_agents}")
            if not dry_run:
                legacy_agents.unlink()

    legacy_refs = legacy_home / "agents-md-references"
    current_refs = agents_home / "agents-md-references"
    if not legacy_refs.is_dir():
        return
    for legacy in legacy_refs.iterdir():
        if not legacy.is_file():
            continue
        existing = legacy.read_text(encoding="utf-8", errors="replace")
        generated = existing.startswith(RUNTIME_AGENT_MARKER)
        current = current_refs / legacy.name
        identical_generated_copy = current.is_file() and legacy.read_bytes() == current.read_bytes()
        if not (generated or identical_generated_copy):
            continue
        print(f"{'Would remove' if dry_run else 'Remove'} legacy generated guidance: {legacy}")
        if not dry_run:
            legacy.unlink()
    if not dry_run and legacy_refs.is_dir() and not any(legacy_refs.iterdir()):
        legacy_refs.rmdir()


def _atomic_write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _apply_plans(plans: list[tuple[Path, str, bool, bool]], replace: bool,
                 dry_run: bool, protected_sources: set[Path]) -> None:
    pending = []
    for destination, content, link, managed in plans:
        resolved_destination = destination.resolve() if destination.exists() else destination.absolute()
        if resolved_destination in protected_sources:
            if link and destination.is_symlink():
                continue
            raise ValueError(f"Destination must not overwrite source: {destination}")
        exists = destination.exists() or destination.is_symlink()
        if destination.is_dir():
            raise ValueError(f"Expected a file, found a directory: {destination}")
        if exists and not link and not destination.is_symlink():
            if destination.read_text(encoding="utf-8") == content:
                continue
        existing_text = (
            destination.read_text(encoding="utf-8", errors="replace")
            if exists and not destination.is_symlink()
            else ""
        )
        generated = bool(existing_text) and (
            existing_text.startswith(GENERATED_MARKER)
            or any(existing_text.startswith(marker) for marker in LEGACY_GENERATED_MARKERS)
        )
        if exists and not replace and not (managed and generated):
            raise ValueError(f"Reconcile existing preferences before --replace-existing: {destination}")
        pending.append((destination, content, link, exists, generated))

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    for destination, content, link, exists, generated in pending:
        print(f"{'Would install' if dry_run else 'Install'} {'symlink' if link else 'generated/reference'}: {destination}")
        if dry_run:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if exists:
            if not generated:
                backup = destination.parent / "guidance-backups" / stamp / destination.name
                backup.parent.mkdir(parents=True, exist_ok=True)
                if destination.is_symlink():
                    _atomic_write(backup, destination.read_text(encoding="utf-8"))
                else:
                    shutil.copy2(destination, backup)
            destination.unlink()
        if link:
            destination.symlink_to(next(iter(protected_sources)))
        else:
            _atomic_write(destination, content)
        assert destination.read_text(encoding="utf-8") == (
            next(iter(protected_sources)).read_text(encoding="utf-8") if link else content
        )


def install(source: Path, agents_home: Path, claude_home: Path,
            replace: bool = False, dry_run: bool = False,
            opencode_home: Path | None = None) -> None:
    source = source.resolve(strict=True)
    if not source.is_file() or not source.read_text(encoding="utf-8").strip():
        raise ValueError("Source must be a nonempty UTF-8 guidance file")
    agents = agents_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = agents_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")
    wrapper = ("Before responding or taking action, read the complete shared personal "
               f"instructions at `{source.as_posix()}` and follow them for this task. "
               "If the file cannot be read, report the missing source. "
               "Edit that repository source when updating these rules, not this wrapper.\n")
    # Claude treats the remainder of a one-line import as the path, including
    # spaces. Codex uses a symlink and OpenCode stores a JSON string.
    imports = f"@{source.as_posix()}\n"
    plans = [(agents, wrapper, os.name != "nt"), (claude, imports, False)]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(p, str) for p in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        if source.as_posix() not in instructions:
            data["instructions"] = [*instructions, source.as_posix()]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False))
    _apply_plans([(path, content, link, False) for path, content, link in plans],
                 replace, dry_run, {source})


class GuidanceComponent:
    def __init__(self, path: Path, text: str, children: tuple["GuidanceComponent", ...] = ()) -> None:
        self.path = path
        self.text = text
        self.children = children


def _load_manifest(manifest_path: Path) -> list[GuidanceComponent]:
    manifest_path = manifest_path.resolve(strict=True)
    root = manifest_path.parent
    data = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Guidance manifest must be a mapping")
    raw_components = data.get("components")
    if not isinstance(raw_components, list) or not raw_components:
        raise ValueError("Guidance manifest must declare at least one component")

    seen: set[Path] = set()

    def parse(entry: object) -> GuidanceComponent:
        if isinstance(entry, str):
            relative = entry
            raw_children: list[object] = []
        elif isinstance(entry, dict):
            relative = entry.get("path")
            raw_children = entry.get("children", [])
            if not isinstance(relative, str) or not relative.strip():
                raise ValueError("Nested guidance component must declare a nonempty path")
            if not isinstance(raw_children, list):
                raise ValueError(f"children must be a list for guidance component: {relative}")
        else:
            raise ValueError("Guidance components must be paths or {path, children} mappings")

        source = (root / relative).resolve(strict=True)
        if source in seen:
            raise ValueError(f"Duplicate guidance component in manifest: {relative}")
        text = source.read_text(encoding="utf-8").strip()
        if not text:
            raise ValueError(f"Guidance component must be nonempty: {source}")
        seen.add(source)
        return GuidanceComponent(source, text, tuple(parse(child) for child in raw_children))

    return [parse(entry) for entry in raw_components]


def _flatten_components(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...]) -> list[GuidanceComponent]:
    flattened: list[GuidanceComponent] = []
    for component in components:
        flattened.append(component)
        flattened.extend(_flatten_components(component.children))
    return flattened


def _component_heading(component: GuidanceComponent) -> tuple[str, str]:
    heading_match = re.search(r'^#\s+(.+)$', component.text, flags=re.MULTILINE)
    if not heading_match:
        raise ValueError(f"Guidance component must declare an H1 heading for TOC generation: {component.path}")
    heading = heading_match.group(1)
    anchor_match = re.search(r'<a id="([^"]+)"></a>', component.text)
    if anchor_match:
        anchor = anchor_match.group(1)
    else:
        anchor = re.sub(r'[^a-z0-9 -]', '', heading.lower())
        anchor = re.sub(r'\s+', '-', anchor.strip())
    return heading, anchor


def _component_toc_lines(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...], depth: int = 0) -> list[str]:
    toc: list[str] = []
    for component in components:
        heading, anchor = _component_heading(component)
        toc.append(f"{'  ' * depth}- [{heading}](#{anchor})")
        toc.extend(_component_toc_lines(component.children, depth + 1))
    return toc


def _demote_markdown_headings(text: str, depth: int) -> str:
    if depth == 0:
        return text
    rendered: list[str] = []
    in_fence = False
    fence_marker = ""
    for line in text.splitlines():
        stripped = line.lstrip()
        marker = stripped[:3]
        if marker in {"```", "~~~"}:
            if not in_fence:
                in_fence = True
                fence_marker = marker
            elif marker == fence_marker:
                in_fence = False
                fence_marker = ""
            rendered.append(line)
            continue
        if not in_fence:
            match = re.match(r'^(#{1,6})(\s+.*)$', line)
            if match:
                level = min(6, len(match.group(1)) + depth)
                line = f"{'#' * level}{match.group(2)}"
        rendered.append(line)
    return "\n".join(rendered)


def _local_toc(component: GuidanceComponent, depth: int) -> str:
    if not component.children:
        return ""
    heading_level = min(6, depth + 2)
    lines = [f"{'#' * heading_level} 🗂️ Contents", ""]
    for child in component.children:
        heading, anchor = _component_heading(child)
        lines.append(f"- [{heading}](#{anchor})")
    return "\n".join(lines)


def _render_component_blocks(components: list[GuidanceComponent] | tuple[GuidanceComponent, ...], depth: int = 0) -> list[str]:
    blocks: list[str] = []
    for component in components:
        blocks.append(_demote_markdown_headings(component.text, depth))
        local_toc = _local_toc(component, depth)
        if local_toc:
            blocks.append(local_toc)
        blocks.extend(_render_component_blocks(component.children, depth + 1))
    return blocks

def install_layered(manifest: Path, agents_home: Path, claude_home: Path,
                    replace: bool = False, dry_run: bool = False,
                    opencode_home: Path | None = None,
                    agents_path_label: str | None = None) -> None:
    manifest = manifest.resolve(strict=True)
    component_tree = _load_manifest(manifest)
    components = _flatten_components(component_tree)
    guidance_root = manifest.parent
    agents_home = agents_home.resolve()
    claude_home = claude_home.resolve()
    if opencode_home is not None:
        opencode_home = opencode_home.resolve()

    component_text = "\n\n".join(_render_component_blocks(component_tree))
    component_toc_text = "\n".join(_component_toc_lines(component_tree))
    manifest_link = Path(os.path.relpath(manifest, start=agents_home)).as_posix()
    component_links = [Path(os.path.relpath(component.path, start=agents_home)).as_posix() for component in components]
    regenerate_link = Path(os.path.relpath(Path(__file__).with_name("regenerate-agents-md.py").resolve(), start=agents_home)).as_posix()
    protected_sources = {component.path for component in components} | {manifest}
    source_lines = [
        "This file is generated atomically from the ordered sources declared in:",
        "",
        f"- [AGENTS.md manifest](<{manifest_link}>)",
        "",
        "Resolved order:",
        "",
        *[f"{index}. [Global guidance component: {component.path.relative_to(guidance_root).as_posix()}](<{link}>)" for index, (component, link) in enumerate(zip(components, component_links), start=1)],
    ]
    source_text = "\n".join(source_lines)
    digest_material = "\0".join([manifest.read_text(encoding="utf-8"), *(component.text for component in components)])
    digest = hashlib.sha256(digest_material.encode()).hexdigest()[:16]
    rendered = (
        f"{GENERATED_MARKER}\n"
        f"<!-- Source digest: {digest} -->\n\n"
        "## 🗂️ Contents\n\n"
        "- [🛠️ Updating this AGENTS.md](#agents-md-maintenance)\n"
        f"{component_toc_text}\n"
        "<a id=\"agents-md-maintenance\"></a>\n"
        "# 🛠️ Updating this AGENTS.md\n\n"
        f"{source_text}\n\n"
        "| When | Then |\n"
        "| --- | --- |\n"
        f"| Updating global agent guidance. | Change the manifest, its canonical components, or generated `agents-md-references/*.md` sources in AgentDesk; do not edit generated files under the agent home directly. Run [`regenerate-agents-md.py`](<{regenerate_link}>) after changing canonical sources. |\n"
        "| A rule determines whether a reference file should be opened. | Put that `when` condition in the applicable AGENTS.md component before the reference is loaded. Put only post-load instructions in the referenced file; do not put sibling-routing or progressive-disclosure logic inside the reference. |\n"
        "| Resolving a relative Markdown link or relative path from this global guidance. | Resolve it relative to the directory containing this `AGENTS.md` (`./AGENTS.md`), never relative to the active working directory. |\n\n"
        f"**AGENTS.md absolute path:** `{agents_path_label or (agents_home / 'AGENTS.md').as_posix()}`\n\n"
        f"{component_text}\n"
    )
    agents = agents_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = agents_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")

    imports = "".join(f"@{component.path.as_posix()}\n" for component in components)
    plans: list[tuple[Path, str, bool, bool]] = [
        (agents, rendered, False, True),
        (claude, imports, False, False),
    ]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(path, str) for path in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        legacy = (guidance_root / "AGENTS.md").resolve(strict=False).as_posix()
        legacy_common = (guidance_root / "common.md").resolve(strict=False).as_posix()
        legacy_overlays = {
            (guidance_root / "macos.md").resolve(strict=False).as_posix(),
            (guidance_root / "windows-wsl.md").resolve(strict=False).as_posix(),
        }
        managed_paths = {legacy, legacy_common, *legacy_overlays, *(component.path.as_posix() for component in components)}
        retained = [path for path in instructions if path not in managed_paths]
        data["instructions"] = [*retained, *(component.path.as_posix() for component in components)]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False, False))
    _apply_plans(plans, replace, dry_run, protected_sources)
    _sync_runtime_agents(guidance_root / "agents-md-references", agents_home / "agents-md-references", dry_run)
    if agents_home == _default_codex_home().resolve():
        _remove_legacy_codex_guidance(Path.home(), agents_home, dry_run)

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--source", type=Path)
    mode.add_argument("--manifest", type=Path)
    parser.add_argument("--codex-home", type=Path, default=_default_codex_home())
    parser.add_argument("--agents-home", dest="codex_home", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--opencode-home", type=Path, default=Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "opencode")
    parser.add_argument("--replace-existing", action="store_true", help="Only after merging old preferences; originals are backed up")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    codex_home = args.codex_home.expanduser()
    if args.source:
        install(args.source, codex_home, args.claude_home, args.replace_existing, args.dry_run, args.opencode_home)
    else:
        install_layered(args.manifest, codex_home,
                        args.claude_home, args.replace_existing, args.dry_run,
                        args.opencode_home)


if __name__ == "__main__":
    main()
