#!/usr/bin/env python3
"""Preview, apply, or roll back AgentDesk global guidance through chezmoi."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "global-guidance" / "agents-md-manifest.yaml"
GENERATED_MARKER = "<!-- Generated by AgentDesk bootstrap-agents-md.py. Do not edit. -->"


def default_state_dir(home: Path) -> Path:
    if os.environ.get("XDG_STATE_HOME"):
        return Path(os.environ["XDG_STATE_HOME"]).expanduser() / "agentdesk-chezmoi-pilot"
    if os.name == "nt" and os.environ.get("LOCALAPPDATA"):
        return Path(os.environ["LOCALAPPDATA"]) / "AgentDesk" / "chezmoi-pilot"
    return home / ".local" / "state" / "agentdesk-chezmoi-pilot"


def relative_codex_home(home: Path, codex_home: Path) -> Path:
    home = home.resolve()
    codex_home = codex_home.resolve()
    try:
        relative = codex_home.relative_to(home)
    except ValueError as error:
        raise ValueError("Pilot CODEX_HOME must be inside the selected home directory") from error
    if len(relative.parts) != 1:
        raise ValueError("Pilot CODEX_HOME must be a direct child of the selected home directory")
    return relative


def source_name(target_name: str) -> str:
    return f"dot_{target_name[1:]}" if target_name.startswith(".") else target_name


def render_source(source: Path, home: Path, codex_home: Path) -> list[Path]:
    relative = relative_codex_home(home, codex_home)
    with tempfile.TemporaryDirectory(prefix="agentdesk-guidance-render-") as temporary:
        temporary_root = Path(temporary)
        rendered_codex = temporary_root / "codex"
        subprocess.run(
            [
                sys.executable,
                str(ROOT / "scripts" / "bootstrap-agents-md.py"),
                "--manifest", str(MANIFEST),
                "--codex-home", str(rendered_codex),
                "--claude-home", str(temporary_root / "claude"),
                "--opencode-home", str(temporary_root / "opencode"),
                "--link-base", str(codex_home),
                "--agents-path-label", str(codex_home / "AGENTS.md"),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
        )
        destination = source / source_name(relative.name)
        destination.mkdir(parents=True)
        shutil.copy2(rendered_codex / "AGENTS.md", destination / "AGENTS.md")
        shutil.copytree(rendered_codex / "agents-md-references", destination / "agents-md-references")

    rendered_references = destination / "agents-md-references"
    return [
        codex_home / "AGENTS.md",
        *(codex_home / "agents-md-references" / path.name for path in sorted(rendered_references.iterdir()) if path.is_file()),
    ]


def chezmoi_command(binary: str, source: Path, home: Path, config: Path, dry_run: bool) -> list[str]:
    command = [
        binary,
        "--source", str(source),
        "--destination", str(home),
        "--config", str(config),
        "--config-format", "json",
        "--no-pager",
        "--color", "off",
        "--verbose",
        "--error-on-conflict=true",
    ]
    if dry_run:
        command.append("--dry-run")
    return [*command, "apply"]


def existing_targets(managed_targets: list[Path]) -> list[Path]:
    return sorted(path for path in managed_targets if path.exists() or path.is_symlink())


def backup_targets(targets: list[Path], managed_targets: list[Path], home: Path, state_dir: Path) -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    backup = state_dir / "backups" / stamp
    files = []
    for target in targets:
        relative = target.resolve().relative_to(home.resolve()) if not target.is_symlink() else target.absolute().relative_to(home.resolve())
        stored = backup / "files" / relative
        stored.parent.mkdir(parents=True, exist_ok=True)
        if target.is_symlink():
            stored.write_text(os.readlink(target), encoding="utf-8")
            kind = "symlink"
        else:
            shutil.copy2(target, stored)
            kind = "file"
        files.append({"path": relative.as_posix(), "kind": kind})
    backup.mkdir(parents=True, exist_ok=True)
    managed = [path.absolute().relative_to(home.resolve()).as_posix() for path in managed_targets]
    (backup / "manifest.json").write_text(
        json.dumps({"managed": managed, "files": files}, indent=2) + "\n",
        encoding="utf-8",
    )
    return backup


def rollback(home: Path, codex_home: Path, state_dir: Path) -> None:
    backups = sorted((state_dir / "backups").glob("*/manifest.json"))
    if not backups:
        raise ValueError(f"No pilot backup found under {state_dir}")
    manifest_path = backups[-1]
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    previous = {entry["path"]: entry for entry in data["files"]}
    for relative in data["managed"]:
        target = home / relative
        if relative not in previous and target.is_file():
            target.unlink()
    for relative, entry in previous.items():
        target = home / relative
        stored = manifest_path.parent / "files" / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.unlink(missing_ok=True)
        if entry["kind"] == "symlink":
            target.symlink_to(stored.read_text(encoding="utf-8"))
        else:
            shutil.copy2(stored, target)
    print(f"Restored pilot backup: {manifest_path.parent}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("plan", "apply", "rollback"))
    parser.add_argument("--home", type=Path, default=Path.home())
    parser.add_argument("--codex-home", type=Path)
    parser.add_argument("--state-dir", type=Path)
    parser.add_argument("--chezmoi-bin", default="chezmoi")
    parser.add_argument("--replace-existing", action="store_true")
    args = parser.parse_args()

    home = args.home.expanduser().resolve()
    codex_home = (args.codex_home or Path(os.environ.get("CODEX_HOME", home / ".codex"))).expanduser().resolve()
    state_dir = (args.state_dir or default_state_dir(home)).expanduser().resolve()
    relative_codex_home(home, codex_home)

    if args.action == "rollback":
        rollback(home, codex_home, state_dir)
        return

    if shutil.which(args.chezmoi_bin) is None and not Path(args.chezmoi_bin).is_file():
        raise ValueError(f"chezmoi executable not found: {args.chezmoi_bin}")

    with tempfile.TemporaryDirectory(prefix="agentdesk-chezmoi-source-") as temporary:
        temporary_root = Path(temporary)
        source = temporary_root / "source"
        source.mkdir()
        managed_targets = render_source(source, home, codex_home)
        config = temporary_root / "chezmoi.json"
        config.write_text(json.dumps({
            "cacheDir": str(temporary_root / "cache"),
            "persistentState": str(temporary_root / "state.boltdb"),
        }) + "\n", encoding="utf-8")

        subprocess.run(chezmoi_command(args.chezmoi_bin, source, home, config, dry_run=True), check=True)
        if args.action == "plan":
            return

        existing = existing_targets(managed_targets)
        unmanaged = []
        for path in existing:
            if path.name == "AGENTS.md" and path.is_file():
                if not path.read_text(encoding="utf-8", errors="replace").startswith(GENERATED_MARKER):
                    unmanaged.append(path)
            elif path.is_file() and not path.read_text(encoding="utf-8", errors="replace").startswith("<!-- Generated by AgentDesk runtime-mode sync. Do not edit. -->"):
                unmanaged.append(path)
        if unmanaged and not args.replace_existing:
            joined = "\n".join(f"- {path}" for path in unmanaged)
            raise ValueError(f"Refusing to replace unmanaged guidance without --replace-existing:\n{joined}")
        backup = backup_targets(existing, managed_targets, home, state_dir)
        subprocess.run(chezmoi_command(args.chezmoi_bin, source, home, config, dry_run=False), check=True)
        print(f"Applied AgentDesk guidance; rollback backup: {backup}")


if __name__ == "__main__":
    main()
